name: Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # Only run when linted files change
    paths:
      - 'functional-tests/**/*.rs'

permissions:
  contents: read

jobs:
  lint:
    name: Lint Rust source files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Rust version and default components are specified in rust-toolchain.toml
      - name: Install Rust version and required components
        run: rustup component add rustfmt

      - name: Show Rust version
        run: cargo --version

      - name: Run Formatting Check
        run: cargo fmt --check
        working-directory: ./functional-tests
